Myanmar: Separate names
everypolitician-scrapers/myanmar-lower-house-2016 pull request #1
Opened 2016-10-31 17:16 UTC by ondenman

There are multiple occurrences of two names being recorded in the name field. For example, in the data for the membership with the id of "59143f6e3cf2461789e4c78bc54afe74", the name of the person is: "U Phye Ral (or) U Myint Than Htoo”. ( http://api.openhluttaw.org/en/memberships?page=2 )

This commit separates the two parts of the string at 'or'. The first part is treated as the 'official' name. The second part is stored in `:other_name`.

2016-11-01 09:15 UTC, tmtmtmtm requested changes

2016-11-01 09:15 UTC, tmtmtmtm commented on lib/member_formatter.rb
>  class MemberFormatter
I don't really understand what this class is. In what way is it a 'Formatter'?

2016-11-01 09:15 UTC, tmtmtmtm commented on lib/member_formatter.rb
> +    names[1].tidy unless names[1].nil?
What if `names` has more than two elements?

2016-11-01 09:15 UTC, tmtmtmtm commented on lib/member_formatter.rb
> +  field :other_name do
This should probably be `:alternate_names`, so that CSV-to-Popolo will add a `note`, rather than leaving it bare.

2016-11-01 09:15 UTC, tmtmtmtm commented on lib/member_formatter.rb
> +    names[0].tidy
Would be a little cleaner to use `.first` here rather than `[0]`

2016-11-02 11:49 UTC, tmtmtmtm requested changes
NB: You're also still 'require'-ing the Member class under its old name.

2016-11-02 11:49 UTC, tmtmtmtm commented on lib/member.rb
> +    names.drop(1).map(&:tidy).join(';') unless names[1].nil?
would probably be simpler and clearer to `to_a` these first rather than testing `names[1]`

2016-11-02 11:49 UTC, tmtmtmtm commented on lib/members.rb
>    def to_a
I think you should fix up some of the issues with the existing scraper first — e.g. replacing this `to_a` with a `members` field on a serialized MembersPage class — then come back to making this PR.

2016-11-02 17:41 UTC, ondenman commented
Closing in favour of: https://github.com/everypolitician-scrapers/myanmar-lower-house-2016/pull/4

2016-11-02 17:41 UTC, closed without merging