Refactor for scraped
everypolitician-scrapers/myanmar-lower-house-2016 pull request #8
Opened 2017-02-21 12:21 UTC by ondenman

Refactors for use with scraped. Part of: https://github.com/everypolitician/everypolitician-data/issues/4161

Scrapes a JSON source.

* [ ] 1. scraper is on Morph.io under the "everypolitician-scrapers" group?
* [ ] 2. scraper's GitHub "Website" link points at morph.io page?
* [ ] 3. scraper is set to auto-run?
* [ ] 4. scraper is archiving?
* [ ] 5. legislature has a scraper webhook set?

2017-02-22 11:53 UTC, tmtmtmtm requested changes
if this is replacing #6 it should note that, and the other one should be closed down. As before, I'd like some feedback from @chrismytton on the approach here, though I suspect you're also doing too much in one PR here. Assuming the test you're adding are meant to pass both before and after this PR, I'd suggest adding them separately (especially as they're highlighting some issues that we will need to decide whether should be fixed before or after this refactoring)

2017-02-23 09:56 UTC, ondenman commented
@tmtmtmtm I've added tests to run before and after the refactoring. Should I open a separate PR for the 'before' tests?

2017-02-23 10:07 UTC, tmtmtmtm commented
@ondenman I'm not entirely sure what you mean here. The basic principle is that a refactoring should have no change in visible behaviour, only in implementation. So any tests that would pass before the refactoring should also pass afterwards, and vice versa. My suggestion was that rather than adding tests in the same PR as the refactoring, you should add those tests separately, first, as they're clearly of value independently from the refactoring, and will also help show that the refactoring has not impacted them.

2017-03-02 17:39 UTC, ondenman commented
@tmtmtmtm I'm not quite sure what you mean. If I  added the tests first they would need rewriting in the refactoring PR to handle the difference in the initialisation of the page objects. That is, `Members.new(members_url)` vs `Members.new(response: Scraped::Request.new(url: url).response)`. Doing so would cause the refactor to fail `ensure-regression-tests` --  unless I dropped 'refactor' from the branch name. Should I instead drop the tests from this PR and add them in a separate PR _after_?

2017-03-03 09:57 UTC, tmtmtmtm commented
@ondenman I think this is another sign that there's too much going on here for a single PR. 

@chrismytton what's your thinking on either adding a `Scraped::JSON` to the core of `scraped`, or as a separate gem? This PR is a useful proof of concept, but the implementation shouldn't really live here.

2017-03-30 18:31 UTC, ondenman commented
Closing in favour of: https://github.com/everypolitician-scrapers/myanmar-lower-house-2016/pull/14

2017-03-30 18:36 UTC, closed without merging